option: fulltune
r: 8
batch_size: 8
model: bert-tiny
dropout_rate: 0.1
lr: 0.001
epochs: 1
num_classes: 1
num_classes_translation_task: 1
language: en,es,de,nl,pt
lang_pairs: en-es #,en-de,en-nl,en-pt
model_output_path: models/
model_name: tiny_bert_multitask_v3
model_path: models/tiny_bert_multitask_v3.pt